services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - VERSION=docker
      - PLEX_CLAIM=claim-gsk7Exzaa834db22SuWP
    volumes:
      - ./plex:/config
      - /home/henrique/downloads/tv:/tv
      - /home/henrique/downloads/movies:/movies
    restart: unless-stopped