networks:
  server-net:
    external: true

volumes:
  vault_data:

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      SIGNUPS_ALLOWED: "true"
    volumes:
      - vault_data:/data/
    ports:
      - "8022:80"
    networks:
      - server-net

