services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - QUEUE_CONNECTION= #optional
    volumes:
      - bookstack_data:/config
    ports:
      - 8020:80
    restart: unless-stopped
    networks:
      - server-net

networks:
  server-net:
    external: true

volumes:
  bookstack_data:
