nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /home/henrique/externo/nextcloud/config:/config
      - /home/henrique/externo/nextcloud:/data
    ports:
      - 443:443
    restart: unless-stopped
    networks:
      - server-net

networks:
  server-net:
    external: true