networks:
  databases-net:
    external: true

volumes:
  redisinsight_data:

services:
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    networks:
      - databases-net
    depends_on:
      - redis